### ISSUE TITLE
qgis3 plugin fails on compressed project (qgz)

### ISSUE THREAD

**Issue by landam** [gislab-npo/gisquick-qgis-plugin#14]
When storing project in compressed file (qgz) the plugin fails after pressing 'Next' button with

```
Traceback (most recent call last):
  File "/home/martin/git/gislab-npo/gisquick-qgis-plugin/publish.py", line 328, in validate
    self.publish_project()
  File "/home/martin/git/gislab-npo/gisquick-qgis-plugin/publish.py", line 284, in publish_project
    project_data = fin.read()
  File "/usr/lib/python3.7/codecs.py", line 701, in read
    return self.reader.read(size)
  File "/usr/lib/python3.7/codecs.py", line 504, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 10: invalid start byte
```

**Comment by landam** [comment]
With c0b0abb the plugin informs the user about unsupported QGZ projects...

![Screenshot from 2019-09-27 22-49-45](https://user-images.githubusercontent.com/5683186/65801485-7dd64e80-e179-11e9-85a0-76c5df89c85b.png)
