### ISSUE TITLE
Key error on start

### ISSUE THREAD

**Issue by ruz76** [gislab-npo/gisquick-qgis-plugin#18]
Traceback (most recent call last):
              File "/home/jencek/qgis3_profiles/profiles/default/python/plugins/gisquick-qgis-plugin/wizard.py", line 30, in _initialize_page
              self.initialize()
              File "/home/jencek/qgis3_profiles/profiles/default/python/plugins/gisquick-qgis-plugin/project.py", line 492, in initialize
              resolutions = self.plugin.project_layers_resolutions()
              File "/home/jencek/qgis3_profiles/profiles/default/python/plugins/gisquick-qgis-plugin/webgisplugin.py", line 280, in project_layers_resolutions
              wmsc_layers_scales = self.resolutions_to_scales(project_tile_resolutions)
              File "/home/jencek/qgis3_profiles/profiles/default/python/plugins/gisquick-qgis-plugin/webgisplugin.py", line 217, in resolutions_to_scales
              return resolutions_to_scales(resolutions, self.map_units())
              File "/home/jencek/qgis3_profiles/profiles/default/python/plugins/gisquick-qgis-plugin/webgisplugin.py", line 195, in map_units
              }[self.iface.mapCanvas().mapUnits()]
             KeyError: 6

**Comment by ruz76** [comment]
Changing to EPSG:3857 did not produce the error. The original data were in EPSG:4326.
